name: AI Interview Coach CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
          node-version: 20

       - name: Install backend dependencies
         run: npm install
         working-directory: Backend

       - name: Install frontend dependencies
         run: npm install
         working-directory: Frontend

       - name: Lint frontend
         run: npm run lint
         working-directory: Frontend

       - name: Build frontend
         run: npm run build
         working-directory: Frontend
